### ISSUE TITLE
Collection modified

### ISSUE THREAD

**Issue by theo2f** [wfletcher/EasyGIS.NET#71] opened 2022-07-08 18:02 UTC
Hi Winston.
My app do modifications on map through threads. Many times the map show the big red X because this error:

> Message: Collection was modified; enumeration operation may not execute.
Message (StackTrace):    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at EGIS.Controls.SFMap.RenderShapefiles() in C:\....\EGIS.Controls\SFMap.cs:line 1720
   at EGIS.Controls.SFMap.OnPaint(PaintEventArgs e) in C:\....\EGIS.Controls\SFMap.cs:line 1838
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

To solve this, on SFMap.cs I changed all foreach statements with layers collection to convert to array, like this:
> _foreach (ShapeFile sf in layers.ToArray()) { ... }_

By this way the iteration is through a copy of list. The error stopped.

I think that's a good thing to change on the project.

**Comment by DaveInCaz** [comment] 2022-07-08 18:06
In other places I've seen people use `ToList` for the same reason, instead of `ToArray`. I imagine for small data sets it doesn't matter, but I wonder which is more appropriate in these contexts? Would there be a performance difference? 

As a guess I would have thought `ToArray` would be a good choice, except having seen so many examples to the contrary.

**Comment by theo2f** [comment] 2022-07-08 18:26
SFMap.ShapeFilesLayers property is already a List<ShapeFile> object and is not allow convert with ToList again.

About performance between ToArray() and ToList():
https://www.meziantou.net/copying-a-collection-tolist-vs-toarray.htm

**Comment by DaveInCaz** [comment] 2022-07-08 18:54
`ToList` is an extension method on `IEnumerable<>` which `List<>` implements, so I'm pretty sure you could use it on a list object.

**Comment by theo2f** [comment] 2022-07-08 18:59
> `ToList` is an extension method on `IEnumerable<>` which `List<>` implements, so I'm pretty sure you could use it on a list object.

![image](https://user-images.githubusercontent.com/5304192/178054175-30e11134-3987-4206-bf73-96ee98ec9ab0.png)

**Comment by theo2f** [comment] 2022-07-08 20:13
Maybe is missing Linq on using clauses... anyway array is a bit more efficient here.

**Comment by wfletcher** [comment] 2022-07-09 05:35
While your proposed solution solves your problem, I think that the cause of the exception is because you are calling methods on the SFMap control from different threads. **In short, don't do this.**

WinForms and WPF/Silverlight doesn't allow access to controls from multiple threads and many .NET controls will throw an InvalidOperationException if you do. In the SFMap control I have not been so stringent and I am not checking the thread and throwing an exception, however you should still only call SFMap method on the thread that created the control - the main UI thread. The ShapeFile class documentation states that the class is not thread safe and given that the SFMap layers are a collection of ShapeFile objects accessing the SFMap control from multiple threads is unpredictable.

There are many articles on access controls from multiple threads and solutions.
https://stackoverflow.com/questions/7609839/accessing-a-forms-control-from-a-separate-thread
https://docs.microsoft.com/en-us/dotnet/desktop/winforms/controls/how-to-make-thread-safe-calls?view=netdesktop-6.0

Possible solutions are using Invoke or a TaskFactory.

```
var uiScheduler = TaskScheduler.FromCurrentSynchronizationContext();
// Construct a new TaskFactory using our UI scheduler
var uiTaskFactory = new TaskFactory(uiScheduler);

//...
//call the SFMap control from separate thread
uiTaskFactory.StartNew(() =>
{
//call sfMap method 
 }
 );

```

**Comment by theo2f** [comment] 2022-07-09 14:42
Winston, sorry, maybe I didn't explain the problem correctly.  
The problem is not directly related to the thread, as this already happened before I created a thread to perform the action.  

When a certain functionality is activated, my map updates every 5 seconds for certain layers. 
The problem occurs at this moment of the update, when the map is being loaded (inside the foreach) and the list is modified.  
Converting to array immediately stopped this problem.  

I will test TaskFactory and comment here later.  

About the use of ToArray, is there any big performance loss in using it?  

Thank you for now.

**Comment by wfletcher** [comment] 2022-07-10 03:25
I have tried to reproduce the issue, but I can't seem to replicate the error. Not saying the error is not there, but there may be some specific sequence that is the cause.

I don't see any performance problems with the use of ToArray in the foreach loops, and if it is solving an error that may be there in specific circumstances I will merge your pull request

**Comment by theo2f** [comment] 2022-07-11 13:48
Winston, I created a new and clean project to try to reproduce the error. I can't reproduce.
I'll make more test to identify, but this will be a bit harder now because I'll put in production the version with .ToArray() to solve the problem.
Even though I can't reproduce it, I know that somehow this is happening. I will find the right way to reproduce this.

**Comment by wfletcher** [comment] 2022-09-05 21:53
Closing as appears to be non issue

**Closed by wfletcher** 2022-09-05 21:53 UTC
