### ISSUE TITLE
PolygonZ Shape File Findigs

### ISSUE THREAD

**Issue by dusko23** [wfletcher/EasyGIS.NET#47] opened 2022-03-24 13:33 UTC
**PolygonZ** type (supported by Egis Library)  
raises and Error when calling the following function on  PolygonZ shape file.
![image](https://user-images.githubusercontent.com/26789352/159926632-f283fc66-d08d-476e-94ef-f34ac9cc031c.png)

The following error is shown
**The method or operation is not implemented.**

**Comment by wfletcher** [comment] 2022-03-25 22:39
This is a duplicate of #38 and has been fixed. You can download the latest source code or wait for the next release

**Comment by wfletcher** [comment] 2022-04-05 11:08
duplicate. Closing

**Closed by wfletcher** 2022-04-05 11:08 UTC

**Comment by dusko23** [comment] 2022-10-11 08:54
Thanks for the update Winston, will wait for a new release. Cany you please
give an estimate of when it might be released and will the mouse wheel be
under developer control as well?
Regards, Dusan
